language: perl
matrix:
    fast_finish: true
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm -n ExtUtils::MakeMaker
  - cpanm -qn Test::Requires::Git
  - cpanm -qn Devel::Cover::Report::Codecov
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
script:
  perl Makefile.PL && PERL5OPT=-MDevel::Cover make test && cover -report codecov
